import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  zoomControls: {
    position: 'absolute',
    right: 20,
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    zIndex: 10,
  },
  zoomButton: {
    width: 40,
    height: 40,
    border: '1px solid rgba(255, 255, 255, 0.2)',
    borderRadius: 4,
    background: 'rgba(0, 0, 0, 0.7)',
    color: '#fff',
    fontSize: 20,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: 'system-ui',
  },
  legend: {
    position: 'absolute',
    right: 20,
    bottom: 120,
    background: 'rgba(0, 0, 0, 0.7)',
    padding: '8px 12px',
    borderRadius: 4,
    border: '1px solid rgba(255, 255, 255, 0.1)',
    zIndex: 10,
  },
  legendTitle: {
    color: 'rgba(255, 255, 255, 0.6)',
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    marginBottom: 4,
  },
  legendGradient: {
    width: 80,
    height: 8,
    background: 'linear-gradient(to right, hsl(240, 80%, 50%), hsl(120, 80%, 50%), hsl(60, 80%, 50%), hsl(0, 80%, 50%))',
    borderRadius: 2,
  },
  legendLabels: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.5)',
    marginTop: 2,
  },
  trajectoryInfo: {
    position: 'absolute',
    left: 20,
    bottom: 20,
    background: 'rgba(0, 0, 0, 0.7)',
    padding: '6px 12px',
    borderRadius: 4,
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.6)',
    fontFamily: 'system-ui',
    zIndex: 10,
  },
};
